@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class Tutorial


class Student {
    name: String
    studentId: String
    phone: String
    email: String
    handle: String
}
class Tutorial {
    name: String
}

class Assignment {
    dueDate: Datetime
}

class Attendance {
    weekNo: int
}

class Submission

enum "<<enumeration>>\nSubmissionStatus" as State {
    SUBMITTED
    NOT_SUBMITTED
    GRADED
}
}

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager --> "*" Tutorial : filters >
ModelManager --> "*" Student : filters >
ModelManager --> "*" Submission : filters >
ModelManager --> "*" Attendance : filters >

Tutorial "1" *--> "*" Assignment

Tutorial "*" -- "*" Student
(Tutorial, Student) .. Attendance

Student "*" -right- "*" Assignment
(Student, Assignment) .. Submission

Submission --> State
@enduml
