@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class Tutorial


class Student {
    name: String
    studentID: String
    phone: String
    email: String
    handle: String
}
class Tutorial {
    name: String
}

class Assignment {
    dueDate: Datetime
}

class Attendance {
    weekNo: int
    lessonNo: int
}

class Submission

enum "<<enumeration>>\nState" as State {
    COMPLETED
    VALID_REASON
    NOT_COMPLETED
}
}

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager --> "*" Tutorial : filters >
ModelManager --> "*" Student : filters >

Student "*" <--> "*" Tutorial
Tutorial "1" *--> "*" Assignment
Attendance "*" <-right- "1" Student
Attendance "*" <-- "1" Tutorial

Student "*" -- "*" Assignment
(Student, Assignment) .. Submission

Submission --> State
@enduml
